### ISSUE TITLE
Define Integration of OGC API Coverages and OGC API Maps into eoAPI

### ISSUE THREAD

**Issue by j08lue** [EOEPCA/data-access#1]
We are planning to extend eoAPI with OGC API Coverages and OGC API Maps services.

We need to define how that integration will look like, so we can design and document the target architecture.

## Acceptance criteria

- [x] Recorded details of integration
- [ ] Documented the target architecture

**Comment by j08lue** [comment]
Based on my understanding, the architecture of the building block will look somewhat like this:

![image](https://github.com/EOEPCA/data-access/assets/3404817/f5757dd5-ae94-45fc-b3c4-e7addf2e7a06)

i.e. each library, eoAPI and Stacture+Terravis, is included in its own right in the building block and, in default configuration, provide a complementary set of endpoints. Stacture+Terravis connects to eoAPI's STAC API.

**Comment by jonas-eberle** [comment]
@j08lue @Schpidi @jankovicgd 

I think this is already completed?

**Comment by j08lue** [comment]
Correct, and documented here: https://eoepca.readthedocs.io/projects/data-access/en/latest/design/overview/
