### ISSUE TITLE
Spike: How to implement support for STAC render extension

### ISSUE THREAD

**Issue by danielfdsilva** [EOEPCA/data-access#57]
I did some research/experimentation around the render extension and here are some thoughts.
There are 2 parts to the render extension, the rendering itself and the form to add/edit the render.

The render is pretty straightforward:
  - The render options on a collection act like a summary of the options available on the items. (like item_assets)
  - Render options can also exist at the collection level to be used to render mosaics.
  - The render options are passed to the tiler as query parameters.
  - Each item may have different render options, but the ones available in the collection can also be available for that item.

The form is a bit more complex.
- The extension spec defines a [JSON schema](https://github.com/stac-extensions/render/tree/main/json-schema) for the properties. This schema could be used to create the form, but we'd need to implement a full JSON schema form renderer. (libraries exist with more or less customization options).
- The spec specifies that additional properties are allowed, and these properties can be of any type, meaning that this form could itself become a form builder.
  - Imagine that a custom property is an array of objects, where each property of the object is some kind of field. Building this would be quite complex.

Options:
1. Full implementation of the JSON schema form renderer.
2. Hardcode the fields in the app. Form becomes highly controlled, but less flexible.
3. Create a faux schema rendered where only certain fields types, and nested levels, are allowed:
    - string, boolean, array of strings (with any level of nesting), and objects with string keys and string values. (like a custom colormap)

I think option 3 is the best for now. It allows for flexibility, but also control.  
Query parameters passed to a tiler will likely not be infinitely nested, and with this option we still allow for the schema to be defined/updated through the extension spec.

**Comment by j08lue** [comment]
NB: Render extension editing support is part of the STAC Admin UI requirements 
- https://github.com/EOEPCA/data-access/issues/52

**Comment by emmanuelmathot** [comment]
> I think option 3 is the best for now. It allows for flexibility, but also control.
> Query parameters passed to a tiler will likely not be infinitely nested, and with this option we still allow for the schema > to be defined/updated through the extension spec.

I agree. STAC render extension is already quite exhaustive about the fields of a render object. Skipping the additional properties in this implementation should be sufficient IMO.

**Comment by j08lue** [comment]
Nice layout of the options.

Were you asking for opinions regarding the form implementation, @danielfdsilva? 😄 I'd also ask for @oliverroick's then...

Sounds wise to keep it simple (option 3).

But we will probably want to support more extension in the future - many of the same as the [Planetary Computer STAC](https://planetarycomputer.microsoft.com/api/stac/v1) is using, I would say. Would it then be better to invest in building off of the [JSON schema](https://github.com/stac-extensions/render/tree/main/json-schema) (option 1) anyways?

**Comment by oliverroick** [comment]
I’m personally not a fan of JSON Schema editors out there, they’re clunky and not that user-friendly. A custom implementation will probably produce better results. 

It’s best to think about this in a bigger context and also consider the requirements for supporting extensions in general, not just the render extension. If you solve this problem right for the render extension it will be easier to support other extensions in the future. 

The main consideration for an editor that supports STAC extensions is that you don’t want all fields to editable. If you look at the [eo extension](https://github.com/stac-extensions/eo), the cloud cover value should probably be inferred from the data when the item is created and not manually edited afterwards. Likewise, the histogram field of the [raster extension](https://github.com/stac-extensions/raster) should be set once and not changed. 

My thinking was to keep a list of popular extensions and their fields, with flags for whether the field should be editable and what form component should be rendered. [stac-fields](https://github.com/radiantearth/stac-spec) does this as well, they keep a [huge JSON document](https://github.com/stac-utils/stac-fields/blob/main/fields.json) with all the definitions on file.

**Comment by j08lue** [comment]
Closed with

- https://github.com/EOEPCA/data-access/issues/73
