### ISSUE TITLE
Add more sample data to eoAPI

### ISSUE THREAD

**Issue by j08lue** [EOEPCA/data-access#75]
For testing the coverages API etc, we could use some more sample data in our [eoAPI dev catalog](https://eoapi.develop.eoepca.org/).

A good example would be multi-spectral data, ideally Sentinel-2 L2A.

Since the EOEPCA+ Kubernetes cluster is deployed in CreoDIAS, perhaps we could even load assets directly from the Sentinel-2 collection in CreoDIAS' S3? 

They have a STAC catalog: https://pgstac.demo.cloudferro.com/collections/sentinel-2-l2a/items

It keeps the cloud-loadable asset hrefs under "alternate assets", which TiTiler-PgSTAC currently does not support.
- https://github.com/stac-utils/titiler-pgstac/discussions/181

But we could probably work around that - we will probably want to copy the STAC items to our catalog anyways.

Either way, a small subset of Sentinel-2 L2A scenes would be great to include. It can be regionally and temporally limited, perhaps even just 2x2 MGRS tiles for a year or so.

## Acceptance criteria

- [ ] EOEPCA eoAPI STAC has a collection of Sentinel-2 L2A scenes that we can use to test / demo TiTiler and Stacture with

**Comment by j08lue** [comment]
Ok, the CDSE Sentinel-2 L2A data are in JPEG2000. Performance / efficiency of reading overviews from those is not great, as @vincentsarago documented [here](https://medium.com/@_VincentS_/do-you-really-want-people-using-your-data-ec94cd94dc3f).

What alternatives do we have? Looking at the CloudFerro STAC https://radiantearth.github.io/stac-browser/#/external/https://pgstac.demo.cloudferro.com - the only collection with COGs seems to be [Sentinel-1 Ground Range Detected (GRD)](https://radiantearth.github.io/stac-browser/#/external/pgstac.demo.cloudferro.com/collections/sentinel-1-grd).

It uses the `alternate assets` extension for S3 links, too.

**Comment by j08lue** [comment]
We may need to add alternate assets support to eoapi-k8s:

- https://github.com/developmentseed/eoapi-k8s/issues/137

As discussed here:

- https://github.com/stac-utils/titiler-pgstac/discussions/181

**Comment by jonas-eberle** [comment]
> Ok, the CDSE Sentinel-2 L2A data are in JPEG2000. Performance / efficiency of reading overviews from those is not great, as @vincentsarago documented [here](https://medium.com/@_VincentS_/do-you-really-want-people-using-your-data-ec94cd94dc3f).

This blog post is quite old. Are the results still valid? The visualization services from Sinergise and Copernicus Dataspace Ecosystem use the JPEG2000 format. 

> What alternatives do we have? Looking at the CloudFerro STAC https://radiantearth.github.io/stac-browser/#/external/https://pgstac.demo.cloudferro.com - the only collection with COGs seems to be [Sentinel-1 Ground Range Detected (GRD)](https://radiantearth.github.io/stac-browser/#/external/pgstac.demo.cloudferro.com/collections/sentinel-1-grd).

Sentinel-1 is not an option as you need to conduct some pre-processing steps.

**Comment by vincentsarago** [comment]
> This blog post is quite old. Are the results still valid? The visualization services from Sinergise and Copernicus Dataspace Ecosystem use the JPEG2000 format.

If I remember well Sinergise use a proprietary driver to read the JPEG2000. GDAL maintainers did some improvement in GDAL and OpenJPEG drivers but this is still not as efficient as COG. 

> Sentinel-1 is not an option as you need to conduct some pre-processing steps.

What kind of pre-processing? you can visualize Sentinel-1 GRD which are stored as COGs

**Comment by j08lue** [comment]
The GRD data CloudFerro hosts is already terrain-corrected, at least. The thumbnails they reference look ok?

**Comment by MathewNWSH** [comment]
> Note on CreoDIAS access from TiTiler deployed in EOEPCA k8s: fundamentally, we should have access. Might need to generate some kind of credentials (@rconway knows).

s3 key gen on CDSE (free with predefined monthly quota limits) https://documentation.dataspace.copernicus.eu/APIs/S3.html
s3 key extraction on Creodias (data transfer is not limited even on the smallest machines) https://creodias.docs.cloudferro.com/en/latest/eodata/How-to-get-credentials-used-for-accessing-EODATA-on-a-cloud-VM-on-Creodias.html

hope this will help

**Comment by j08lue** [comment]
Regarding which subset, anything easy enough to handle is fine.
* 2024 to date, all of Europe?
* past 3 years, whatever country/region - Iceland? 🤷 🇮🇸 🌋 🧊

**Comment by j08lue** [comment]
Btw, the [collection](https://pgstac.demo.cloudferro.com/collections/sentinel-2-l2a) metadata also needs a bit of cleanup after removing the alternate assets: `item_assets` and `auth:schemes` and perhaps `stac_extensions`.

**Comment by ciaransweet** [comment]
So once a subset is decided:

* Grab the collection + items
* For every asset in an item, replace its `href` with the `alternate:s3` href, swap its `auth` for the alternates
* Not sure where `"description": "S3 storage provided by CloudFerro Cloud and OpenTelekom Cloud (OTC). Use endpoint URL `https://eodata.dataspace.copernicus.eu`.",` would live on the item? It appears to be a property on the alternate entry but I couldn't see where it would live on the asset after?
* Do the collection changes @j08lue just posted

**Comment by MathewNWSH** [comment]
> Regarding which subset, anything easy enough to handle is fine.
> 
>     * 2024 to date, all of Europe?
> 
>     * past 3 years, whatever country/region - Iceland? 🤷 🇮🇸 🌋 🧊

Since pgstac.demo.cloudferro.com is still in development and the S2L2A collection consists of only a few items, here is a JSON file containing 9,352 (one missing product: /eodata/Sentinel-2/MSI/L2A/2023/03/29/S2B_MSIL2A_20230329T100629_N0509_R022_T33UWV_20230329T130657.SAFE) products intersecting with Poland's geometry, ranging from content_start_date >= '2023-01-01 00:00:00' to content_start_date < '2024-01-01 00:00:00'.

file size -> 656.5 MB
Hope it will help:
https://s3.fra1-2.cloudferro.com/swift/v1/poland-stac/poland-data.json

**Comment by j08lue** [comment]
Ah, was not aware, thank you!

Poland 2023 works, let's see whether we need to subset further if 9k is too much for a quick fix.

**Comment by ciaransweet** [comment]
@MathewNWSH are you able to export this as a list of items in JSON? 

I can't load it with `json.load()` right now..

**Comment by ciaransweet** [comment]
> @ciaransweet
> 
> Each line consists of a STAC JSON item. The following works for me to print the first STAC item: `head -n1 poland-data.json | jq . | less`

Sure, it would be nice if it was wrapped into a json array to be a bit more 'valid' to read in :D

**Comment by ciaransweet** [comment]
> Understood. The format (ndjson) is used by pypgstac as well. I guess this is why @MathewNWSH has made this format available.

Cool thanks, good to know!

**Comment by MathewNWSH** [comment]
> @MathewNWSH are you able to export this as a list of items in JSON?
> 
> I can't load it with `json.load()` right now..

Yup, I've just loaded it into the pgstac instance using:
```pypgstac load items https://s3.fra1-2.cloudferro.com/swift/v1/poland-stac/poland-data.json```

If you prefer, you can get it in the form of item list using:
https://pgstac.demo.cloudferro.com/collections/sentinel-2-l2a/items?limit=1000
and then using https://pgstac.demo.cloudferro.com/collections/sentinel-2-l2a/items?limit=1000&token=next:sentinel-2-l2a:S2A_MSIL2A_20231123T095321_N0509_R079_T34UCC_20231123T141252 move to another page, and so on.

**Comment by MathewNWSH** [comment]
for 1000 items of s2l2a it takes 1.67 min to reply ;/
quite a lot but on the other hand this collection is the richest in metadata among all sentinels / processing levels

**Comment by ciaransweet** [comment]
No worries :D We should have specified we weren't expecting it for pypgstac and just pystac, but I can work with it knowing it's line delimited, thanks!

**Comment by jonas-eberle** [comment]
> for 1000 items of s2l2a it takes 1.67 min to reply ;/

That is quite slow. The same query for sentinel-2-l2a took 4 seconds (without caching) on my pgstac-based STAC API with a total of 11 million scenes within this collection.

**Comment by MathewNWSH** [comment]
> > for 1000 items of s2l2a it takes 1.67 min to reply ;/
> 
> That is quite slow. The same query for sentinel-2-l2a took 4 seconds (without caching) on my pgstac-based STAC API with a total of 11 million scenes within this collection.

the demo is basing on: https://github.com/stac-utils/stac-fastapi-pgstac/blob/main/docker-compose.yml
deployed via docker compose up. Soon we will move to bare metal server (I'm waiting for postgres 17 release)

this is the sample item of S2L2a, as you can see it's quite huge for a single item:
[S2B_MSIL2A_20240110T100309_N0510_R122_T33UVR_20240110T113053.json](https://github.com/user-attachments/files/16995017/S2B_MSIL2A_20240110T100309_N0510_R122_T33UVR_20240110T113053.json)

I was blaming compose deployment and huge size of an item for performance problems.

Is there any option to exchange experience from using pgstac it with you?

**Comment by jonas-eberle** [comment]
> this is the sample item of S2L2a, as you can see it's quite huge for a single item

Yes, this is quite huge. Our STAC item (generated with `stactools-sentinel2` package) is smaller (we deleted downsampled assets): 
https://stac.terrabyte.lrz.de/public/api/collections/sentinel-2-c1-l2a/items/S2B_MSIL2A_20240110T100309_N0510_R122_T33UVR_20240110T113053

> Is there any option to exchange experience from using stac-fastApi-pgstac with you? Or general recommendations while working with pgstac/stac-fastAPI-pgstac?

Sure. We also have an issue on working on performance improvements and best practice guidelines within EOEPCA (https://github.com/EOEPCA/resource-discovery/issues/23). I just commented there. 

@MathewNWSH Please feel free to contact me via mail as well: jonas.eberle@dlr.de

**Comment by ciaransweet** [comment]
@MathewNWSH just to check I'd not broken anything with some edits to the stac items, I ran them through `pystack.Item.validate()`, I got an error but then double checked to see if it was me who caused it and it looks like the items in the file provided fail the validation anyway:

```
pystac.errors.STACValidationError: Validation failed for Feature with ID S2A_MSIL2A_20230219T100041_N0509_R122_T33UXV_20230219T143227 against schema at https://schemas.stacspec.org/v1.0.0/item-spec/json-schema/item.json
'sentinel-2-l2a' should not be valid under {}

Failed validating 'not' in schema['allOf'][0]['allOf'][2]['else']['properties']['collection']:
    {'not': {}}

On instance['collection']:
    'sentinel-2-l2a'
```

I think because they contain no link to the collection, they can't have the collection id as a property? I'm relatively new to STAC so is this actually an error that is breaking or does pgstac shrug this off?

**Comment by ciaransweet** [comment]
For example, this is the `links` block for `S2A_MSIL2A_20230219T100041_N0509_R122_T33UXV_20230219T143227`

```
  "links": [
    {
      "title": "Product history record from the CDSE traceability service",
      "rel": "version-history",
      "href": "https://trace.dataspace.copernicus.eu/api/v1/traces/name/S2A_MSIL2A_20230219T100041_N0509_R122_T33UXV_20230219T143227.SAFE.zip",
      "type": "application/json"
    }
  ],
```

**Comment by MathewNWSH** [comment]
Hey @ciaransweet

While working with pgstac, it's sufficient to add items in the format I provided. I haven't worked with other STAC implementations besides pgstac.

After querying pgstac using FastAPI (stac-fastapi-pgstac), **it validates requests and data sent to a PgSTAC backend. It also adds links (such as collection and catalog links) to the returned data automatically.**

Regarding the traceability links in the items you mentioned: we add those because it's a feature of CDSE that allows file history tracking. STAC FastAPI handles it well.

Here’s the STAC item you referred to: STAC Browser: Sentinel-2 L2A It seems valid to me:
https://radiantearth.github.io/stac-browser/#/external/https://pgstac.demo.cloudferro.com/collections/sentinel-2-l2a/items/S2A_MSIL2A_20230219T100041_N0509_R122_T33UXV_20230219T143227
![image](https://github.com/user-attachments/assets/b567ea97-eed5-4790-8fd1-2c465c29eb5f)


**If you prefer to work with items in a format I provided above, you can try scraping the JSON replies from the API in chunks.**
Sample raw item -> https://pgstac.demo.cloudferro.com/collections/sentinel-2-l2a/items/S2A_MSIL2A_20230219T100041_N0509_R122_T33UXV_20230219T143227

**Comment by j08lue** [comment]
We have a collection up: `sentinel-2-l2a`

You can browse it here: https://radiantearth.github.io/stac-browser/#/external/eoapi.develop.eoepca.org/stac/collections/sentinel-2-l2a/items/S2B_MSIL2A_20231231T100329_N0510_R122_T33UYU_20231231T110801?.asset=asset-B04_10m

First health check could be to pull basic info about one of the files, for example with this endpoint (see [docs](https://eoapi.develop.eoepca.org/raster/api.html#/STAC%20Item/info_collections__collection_id__items__item_id__info_get))

```
https://eoapi.develop.eoepca.org/raster/collections/{collection_id}/items/{item_id}/info
```

However, when I do that:

```bash
curl -X 'GET' \
  'https://eoapi.develop.eoepca.org/raster/collections/sentinel-2-l2a/items/S2B_MSIL2A_20231231T100329_N0510_R122_T33UYU_20231231T110801/info?assets=B04_10m' \
  -H 'accept: application/json'
```

I get at 500 error with the usual

```json
{
  "detail": "'/vsis3/eodata/Sentinel-2/MSI/L2A/2023/12/31/S2B_MSIL2A_20231231T100329_N0510_R122_T33UYU_20231231T110801.SAFE/GRANULE/L2A_T33UYU_A035612_20231231T100330/IMG_DATA/R10m/T33UYU_20231231T100329_B04_10m.jp2' does not exist in the file system, and is not recognized as a supported dataset name."
}
```

We probably need to add some config, so rio-tiler knows to look in CloudFerro S3, not AWS, right?

**Comment by j08lue** [comment]
Probably a matter of setting

```
AWS_S3_ENDPOINT="https://s3/.{region}.[cloudferro.com](http://cloudferro.com/)"
```

where `region` is probably `waw3-1`, right @MathewNWSH?

**Comment by j08lue** [comment]
I assume it is about adding an `envVars` block to this `settings` list here: https://github.com/EOEPCA/eoepca-plus/blob/e519524f37b748c24ec981cacfc210211708392c/argocd/eoepca/data-access/parts/values/values-eoapi.yaml#L46

**Comment by MathewNWSH** [comment]
> Probably a matter of setting
> 
> ```
> AWS_S3_ENDPOINT="https://s3/.{region}.cloudferro.com"
> ```
> 
> where `region` is probably `waw3-1`, right @MathewNWSH?

Hey @j08lue @jonas-eberle 

eodata.dataspace.copernicus.eu for CDSE
eodata.cloudferro.com for Creodias's clouds waw3-2 and fra1-2

here is how I do it in CDSE:
```python
 os.environ['GDAL_HTTP_TCP_KEEPALIVE'] = "YES"
os.environ['AWS_S3_ENDPOINT'] = "eodata.dataspace.copernicus.eu"
os.environ['AWS_ACCESS_KEY_ID'] = ""
os.environ['AWS_SECRET_ACCESS_KEY'] = ""
os.environ['AWS_HTTPS'] = "YES"
os.environ['AWS_VIRTUAL_HOSTING'] = "FALSE"
os.environ['GDAL_HTTP_UNSAFESSL'] = "YES"
```
and this is how I do it from my machine on waw3-2 (should also work on fra1-2 cloud):
```console
export AWS_S3_ENDPOINT=eodata.cloudferro.com
export AWS_ACCESS_KEY_ID=****
export AWS_SECRET_ACCESS_KEY=****
export CPL_CURL_VERBOSE=YES
export AWS_HTTPS=YES
export AWS_VIRTUAL_HOSTING=FALSE
export GDAL_HTTP_TCP_KEEPALIVE=YES
export CPL_VSIL_CURL_CHUNK_SIZE=98304
export GDAL_INGESTED_BYTES_AT_OPEN=16384
export GDAL_HTTP_UNSAFESSL=YES
export CPL_DEBUG=OFF
export GDAL_NUM_THREADS=-1
export PROJ_DEBUG=OFF
```
some of above just improves gdals performance. Here is the output of gdalinfo to mentioned file:

```console
mniemyjski@MNemyjskiNB:~$ gdalinfo /vsis3/eodata/Sentinel-2/MSI/L2A/2023/12/31/S2B_MSIL2A_20231231T100329_N0510_R122_T33UYU_20231231T110801.SAFE/GRANULE/L2A_T33UYU_A035612_20231231T100330/IMG_DATA/R10m/T33UYU_20231231T100329_B04_10m.jp2
Driver: JP2OpenJPEG/JPEG-2000 driver based on OpenJPEG library
Files: /vsis3/eodata/Sentinel-2/MSI/L2A/2023/12/31/S2B_MSIL2A_20231231T100329_N0510_R122_T33UYU_20231231T110801.SAFE/GRANULE/L2A_T33UYU_A035612_20231231T100330/IMG_DATA/R10m/T33UYU_20231231T100329_B04_10m.jp2
Size is 10980, 10980
Coordinate System is:
PROJCRS["WGS 84 / UTM zone 33N",
    BASEGEOGCRS["WGS 84",
        ENSEMBLE["World Geodetic System 1984 ensemble",
            MEMBER["World Geodetic System 1984 (Transit)"],
            MEMBER["World Geodetic System 1984 (G730)"],
            MEMBER["World Geodetic System 1984 (G873)"],
            MEMBER["World Geodetic System 1984 (G1150)"],
            MEMBER["World Geodetic System 1984 (G1674)"],
            MEMBER["World Geodetic System 1984 (G1762)"],
            MEMBER["World Geodetic System 1984 (G2139)"],
            ELLIPSOID["WGS 84",6378137,298.257223563,
                LENGTHUNIT["metre",1]],
            ENSEMBLEACCURACY[2.0]],
        PRIMEM["Greenwich",0,
            ANGLEUNIT["degree",0.0174532925199433]],
        ID["EPSG",4326]],
    CONVERSION["UTM zone 33N",
        METHOD["Transverse Mercator",
            ID["EPSG",9807]],
        PARAMETER["Latitude of natural origin",0,
            ANGLEUNIT["degree",0.0174532925199433],
            ID["EPSG",8801]],
        PARAMETER["Longitude of natural origin",15,
            ANGLEUNIT["degree",0.0174532925199433],
            ID["EPSG",8802]],
        PARAMETER["Scale factor at natural origin",0.9996,
            SCALEUNIT["unity",1],
            ID["EPSG",8805]],
        PARAMETER["False easting",500000,
            LENGTHUNIT["metre",1],
            ID["EPSG",8806]],
        PARAMETER["False northing",0,
            LENGTHUNIT["metre",1],
            ID["EPSG",8807]]],
    CS[Cartesian,2],
        AXIS["(E)",east,
            ORDER[1],
            LENGTHUNIT["metre",1]],
        AXIS["(N)",north,
            ORDER[2],
            LENGTHUNIT["metre",1]],
    USAGE[
        SCOPE["Navigation and medium accuracy spatial referencing."],
        AREA["Between 12°E and 18°E, northern hemisphere between equator and 84°N, onshore and offshore. Austria. Bosnia and Herzegovina. Cameroon. Central African Republic. Chad. Congo. Croatia. Czechia. Democratic Republic of the Congo (Zaire). Gabon. Germany. Hungary. Italy. Libya. Malta. Niger. Nigeria. Norway. Poland. San Marino. Slovakia. Slovenia. Svalbard. Sweden. Vatican City State."],
        BBOX[0,12,84,18]],
    ID["EPSG",32633]]
Data axis to CRS axis mapping: 1,2
Origin = (699960.000000000000000,5900040.000000000000000)
Pixel Size = (10.000000000000000,-10.000000000000000)
Image Structure Metadata:
  COMPRESSION_REVERSIBILITY=LOSSLESS
Corner Coordinates:
Upper Left  (  699960.000, 5900040.000) ( 17d59'40.71"E, 53d12'43.17"N)
Lower Left  (  699960.000, 5790240.000) ( 17d55'40.15"E, 52d13'34.41"N)
Upper Right (  809760.000, 5900040.000) ( 19d38' 3.06"E, 53d 9'33.92"N)
Lower Right (  809760.000, 5790240.000) ( 19d31'51.72"E, 52d10'31.74"N)
Center      (  754860.000, 5845140.000) ( 18d46'18.91"E, 52d41'45.89"N)
Band 1 Block=1024x1024 Type=UInt16, ColorInterp=Gray
  Overviews: 5490x5490, 2745x2745, 1373x1373, 687x687
  Overviews: arbitrary
  Image Structure Metadata:
    COMPRESSION=JPEG2000
    NBITS=15
```

**Comment by MathewNWSH** [comment]
@j08lue 
Also you can create/manage/delete your s3 keys on Creodias using https://eodata-keymanager.creodias.eu/panel/s3-credentials which is the default manager/key generation site for users.

**Comment by j-musial** [comment]
FYI: @j08lue @jonas-eberle 

To generate S3 credentials via Copernicus Data Space Ecosystem (CDSE) please [click here](https://eodata-s3keysmanager.dataspace.copernicus.eu/). <- this is a public endpoint with free quoata
To generate S3 credentials via CREODIAS please [click here](https://eodata-keymanager.creodias.eu/panel/s3-credentials). <- this is a commercial endpoint

All of these S3 keys are external and can be used on any cloud or any computer with Internet access. Region settings does not matter at all.

For CDSE your gdal call should be:

gdalinfo --config AWS_ACCESS_KEY_ID !!YOUR_CDSE_PUBLIC_KEY!!  --config AWS_SECRET_ACCESS_KEY !!YOUR_CDSE_SECRET_KEY!! --config AWS_S3_ENDPOINT eodata.dataspace.copernicus.eu --config AWS_VIRTUAL_HOSTING FALSE /vsis3/eodata/Sentinel-2/MSI/L2A/2023/12/31/S2B_MSIL2A_20231231T100329_N0510_R122_T33UYU_20231231T110801.SAFE/GRANULE/L2A_T33UYU_A035612_20231231T100330/IMG_DATA/R10m/T33UYU_20231231T100329_B04_10m.jp2

For CREODIAS your gdal call should be:

gdalinfo --config AWS_ACCESS_KEY_ID !!YOUR_CREODIAS_PUBLIC_KEY!!  --config AWS_CREODIAS_SECRET_ACCESS_KEY !!YOUR_SECRET_KEY!! --config AWS_S3_ENDPOINT eodata.cloudferro.com --config AWS_VIRTUAL_HOSTING FALSE /vsis3/eodata/Sentinel-2/MSI/L2A/2023/12/31/S2B_MSIL2A_20231231T100329_N0510_R122_T33UYU_20231231T110801.SAFE/GRANULE/L2A_T33UYU_A035612_20231231T100330/IMG_DATA/R10m/T33UYU_20231231T100329_B04_10m.jp2

**Comment by j08lue** [comment]
Thanks for your help @MathewNWSH and @j-musial.

Credentials are working and we are now able to get rendered images from TiTiler directly off of the Sentinel-2 JP2 files, like

https://eoapi.develop.eoepca.org/raster/collections/sentinel-2-l2a/items/S2A_MSIL2A_20230917T100031_N0509_R122_T34UCF_20230917T143103/preview?assets=B04_10m&assets=B03_10m&assets=B02_10m&color_formula=Gamma%20RGB%203.2%20Saturation%200.8%20Sigmoidal%20RGB%2025%200.35&nodata=0

![image](https://github.com/user-attachments/assets/d0628ada-e823-4688-bd7c-a45bf65f0bb5)

We might want to look into the performance optimizations you described above, @MathewNWSH, thanks for sharing!
