### ISSUE TITLE
Activate Grafana dashboard on Data Access building block

### ISSUE THREAD

**Issue by j08lue** [EOEPCA/data-access#76]
- [x] https://github.com/developmentseed/eoapi-k8s/issues/154
- [x] Resolve issues with negative effects on other services in k8s
- [x] Re-enable service

**Comment by j08lue** [comment]
We had the dashboard up, but it is currently down again. Looking into why

- https://github.com/developmentseed/eoapi-k8s/issues/146#issuecomment-2338819807

**Comment by j08lue** [comment]
Done in

- https://github.com/EOEPCA/eoepca-plus/pull/45

**Comment by pantierra** [comment]
Seems like there have been [some issues](https://eoepca.slack.com/archives/C07DKCUV22Z/p1733151911504579):

```
kubectl get apiservice | grep Missi
v1beta1.metrics.k8s.io                               data-access/eoapi-support-metrics-server       False (MissingEndpoints)   12m
```

I just [commented out](https://github.com/EOEPCA/eoepca-plus/commit/f019d4e053ca8286ccefa879ad5022ee51ae2137) the eoapi-support component. We have to look into this a bit more.

**Comment by j08lue** [comment]
@ividito is on it:
> Looks like the same problem as before, but with some additional context - I had tested namespace deletion when I initially redeployed, but the new error messages make me think that it only interferes with namespaces with certain properties.
